create extension if not exists pgcrypto;
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade);
create table if not exists public.teams(id uuid primary key default gen_random_uuid(),name text unique not null,short text,short_name text,coach text,logo text,logo_url text);
create table if not exists public.players(id uuid primary key default gen_random_uuid(),name text not null,team_id uuid references public.teams(id) on delete cascade,position text,number integer,goals integer default 0,image text,image_url text);
create table if not exists public.matches(id uuid primary key default gen_random_uuid(),match_date date not null,match_time time,home_id uuid references public.teams(id),away_id uuid references public.teams(id),status text default 'Scheduled',home_score integer default 0,away_score integer default 0,venue text,check(home_id is null or away_id is null or home_id<>away_id));
create table if not exists public.match_events(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,type text not null default 'goal',minute integer,scorer_id uuid references public.players(id) on delete set null,assister_id uuid references public.players(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.trophies(id uuid primary key default gen_random_uuid(),name text not null,winner text,season text,image text,image_url text);
create table if not exists public.news(id uuid primary key default gen_random_uuid(),title text not null,date date not null,body text not null,image text,image_url text);
alter table public.admin_users enable row level security;alter table public.teams enable row level security;alter table public.players enable row level security;alter table public.matches enable row level security;alter table public.match_events enable row level security;alter table public.trophies enable row level security;alter table public.news enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.admin_users where user_id=auth.uid())$$;
grant select on public.teams,public.players,public.matches,public.match_events,public.trophies,public.news to anon,authenticated;
grant insert,update,delete on public.teams,public.players,public.matches,public.match_events,public.trophies,public.news to authenticated;
grant execute on function public.is_admin() to anon,authenticated;
 drop policy if exists "public teams" on public.teams;
create policy "public teams" on public.teams for select using(true);
 drop policy if exists "admin teams insert" on public.teams; drop policy if exists "admin teams update" on public.teams; drop policy if exists "admin teams delete" on public.teams;
 create policy "admin teams insert" on public.teams for insert to authenticated with check(public.is_admin()); create policy "admin teams update" on public.teams for update to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admin teams delete" on public.teams for delete to authenticated using(public.is_admin());
 drop policy if exists "public players" on public.players;
create policy "public players" on public.players for select using(true);
 drop policy if exists "admin players insert" on public.players; drop policy if exists "admin players update" on public.players; drop policy if exists "admin players delete" on public.players;
 create policy "admin players insert" on public.players for insert to authenticated with check(public.is_admin()); create policy "admin players update" on public.players for update to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admin players delete" on public.players for delete to authenticated using(public.is_admin());
 drop policy if exists "public matches" on public.matches;
create policy "public matches" on public.matches for select using(true);
 drop policy if exists "admin matches insert" on public.matches; drop policy if exists "admin matches update" on public.matches; drop policy if exists "admin matches delete" on public.matches;
 create policy "admin matches insert" on public.matches for insert to authenticated with check(public.is_admin()); create policy "admin matches update" on public.matches for update to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admin matches delete" on public.matches for delete to authenticated using(public.is_admin());
 drop policy if exists "public match_events" on public.match_events;
create policy "public match_events" on public.match_events for select using(true);
 drop policy if exists "admin match_events insert" on public.match_events; drop policy if exists "admin match_events update" on public.match_events; drop policy if exists "admin match_events delete" on public.match_events;
 create policy "admin match_events insert" on public.match_events for insert to authenticated with check(public.is_admin()); create policy "admin match_events update" on public.match_events for update to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admin match_events delete" on public.match_events for delete to authenticated using(public.is_admin());
 drop policy if exists "public trophies" on public.trophies;
create policy "public trophies" on public.trophies for select using(true);
 drop policy if exists "admin trophies insert" on public.trophies; drop policy if exists "admin trophies update" on public.trophies; drop policy if exists "admin trophies delete" on public.trophies;
 create policy "admin trophies insert" on public.trophies for insert to authenticated with check(public.is_admin()); create policy "admin trophies update" on public.trophies for update to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admin trophies delete" on public.trophies for delete to authenticated using(public.is_admin());
 drop policy if exists "public news" on public.news;
create policy "public news" on public.news for select using(true);
 drop policy if exists "admin news insert" on public.news; drop policy if exists "admin news update" on public.news; drop policy if exists "admin news delete" on public.news;
 create policy "admin news insert" on public.news for insert to authenticated with check(public.is_admin()); create policy "admin news update" on public.news for update to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "admin news delete" on public.news for delete to authenticated using(public.is_admin());
insert into storage.buckets(id,name,public) values('league-media','league-media',true) on conflict(id) do update set public=true;
drop policy if exists "media public read" on storage.objects;drop policy if exists "media admin upload" on storage.objects;drop policy if exists "media admin update" on storage.objects;drop policy if exists "media admin delete" on storage.objects;
create policy "media public read" on storage.objects for select using(bucket_id='league-media');
create policy "media admin upload" on storage.objects for insert to authenticated with check(bucket_id='league-media' and public.is_admin());
create policy "media admin update" on storage.objects for update to authenticated using(bucket_id='league-media' and public.is_admin());
create policy "media admin delete" on storage.objects for delete to authenticated using(bucket_id='league-media' and public.is_admin());
create index if not exists match_events_match_id_idx on public.match_events(match_id);
create index if not exists match_events_scorer_id_idx on public.match_events(scorer_id);
create index if not exists match_events_assister_id_idx on public.match_events(assister_id);
-- After creating a Supabase Auth administrator:
-- insert into public.admin_users(user_id) values('YOUR-AUTH-USER-UUID');
